# Generated by Django 4.2.5 on 2023-12-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0004_alter_ott_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
