# Generated by Django 4.2.5 on 2023-12-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0007_category_uploaded_at_subcategory_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
