# Generated by Django 4.2.5 on 2023-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_customuser_bio_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
