# Generated by Django 4.1.13 on 2024-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_customuser_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
