# Generated by Django 4.2.5 on 2023-12-21 04:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusapp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statusapp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 4, 41, 14, 41025, tzinfo=datetime.timezone.utc)),
        ),
    ]
