# Generated by Django 4.2.5 on 2023-12-27 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0002_statusapp_created_at_statusapp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusapp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 11, 3, 25, 812759, tzinfo=datetime.timezone.utc)),
        ),
    ]
